
import { Injectable, signal, computed } from '@angular/core';

type TranslationKey = keyof typeof dictionary.en;

const dictionary = {
  en: {
    title: "SPAD Simulator",
    languageToggle: "EN / 中文",
    runSimulation: "Run Simulation",
    runBackendSimulation: "Backend Simulation Run",
    backendSimulating: "Backend running...",
    backendCompute: "Backend compute",
    backendJobStatus: "Backend job",
    backendUnavailable: "Backend service is offline.",
    backendMode: "Backend",
    observedCounts: "Observed Counts",
    snrDb: "SNR",
    deadTimeLoss: "Dead-Time Loss",
    signalPhotons: "Signal photons:",
    backgroundPhotons: "Scene stray photons:",
    laserSignalRate: "Laser-reflection rate:",
    solarSignalRate: "Solar-reflection rate:",
    saturationWarning: "Detector saturation warning",
    visibilityRatio: "Visibility:",
    payloadOmitted: "Large payload omitted:",
    sampleRate: "Sample rate:",
    refresh: "Refresh",
    simulating: "Simulating...",
    previewTrajectory: "Preview Trajectory",
    downloadData: "Download Data",
    targetParams: "Target Parameters",
    targetType: "Target Type",
    targetTypeBall: "Tennis Ball",
    targetTypeBlade: "Propeller Blade",
    targetTypeDrone: "Drone",
    motionType: "Motion Type",
    motionTypeFixed: "Fixed Position",
    motionTypePath: "Path Planning",
    motionTypeGravity: "Gravity Simulation",
    motionTypeRotation: "Rotation Mode",
    centerX: "Center X",
    altitudeY: "Altitude Y",
    centerZ: "Center Z",
    velX: "Vel X",
    velY: "Vel Y",
    velZ: "Vel Z",
    reflectivity: "Reflectivity (0-1)",
    bodyReflectivity: "Body Reflectivity (0-1)",
    propReflectivity: "Propeller Reflectivity (0-1)",
    restitution: "Restitution (Bounciness)",
    dynamicModulation: "Dynamic Target Modulation",
    bladeLength: "Blade Size / Length (m)",
    rotationRadius: "Rotation Radius (m)",
    rotationSpeed: "Rotation Speed (RPM)",
    rotationSpeedSegment: "Rot. Speed",
    bladePitch: "Blade Pitch (°)",
    dronePitch: "Drone Pitch (°)",
    droneScale: "Drone Scale",
    dronePreset: "Drone Preset",
    droneMass: "Mass:",
    droneMaxSpeed: "Max Speed:",
    droneSize: "Size:",
    droneRotor: "Hover Rotor:",
    manualFlight: "Manual Flight",
    manualSpeed: "Manual Speed",
    capturePose: "Set Current Pose as Start",
    startFlightRecording: "Start Recording",
    stopFlightRecording: "Stop Recording",
    clearFlightRecording: "Clear Recording",
    recordedFlight: "Recorded Flight",
    recordedDuration: "Duration",
    samples: "samples",
    manualFlightState: "Flight Controller State",
    pathPlanning: "Path Planning",
    pathPlanningDesc: "Define a series of waypoints for the target's flight path. Speed can be set for each segment.",
    waypoint: "Waypoint",
    speed: "Speed",
    duration: "Duration",
    addWaypoint: "Add Waypoint",
    remove: "Remove",
    rotationSpeedPlanning: "Rotation Speed Planning",
    rotationSpeedPlanningDesc: "Define time points to create a variable rotation speed profile. RPM will interpolate linearly between points.",
    time: "Time",
    rpm: "RPM",
    addRotationKeyframe: "Add Time Point",
    propeller1: "Propeller 1",
    propeller2: "Propeller 2",
    propeller3: "Propeller 3",
    propeller4: "Propeller 4",
    customBlade: "Custom Propeller Shape",
    customBladeDesc: "Upload an image to use as the target. The shape will be extracted from dark areas. The size is controlled by 'Blade Size'.",
    customBladeRealismDesc: "Grayscale values in the image now modulate reflectivity. Black is full reflectivity, while dark gray areas will appear dimmer in the simulation.",
    originalImage: "Original Image",
    clickToUpload: "Click to Upload",
    extractedShape: "Extracted Shape",
    shapeWillAppear: "Shape will appear here.",
    detectorParams: "Detector Parameters",
    detectorPreset: "Detector Preset",
    detectorPresetCustom: "Custom detector",
    pixelPitch: "Pixel Pitch:",
    pdpAtWavelength: "PDP at Wavelength:",
    deadTime: "Dead Time:",
    irfFwhm: "IRF FWHM:",
    resWidth: "Res. Width",
    resHeight: "Res. Height",
    fov: "Field of View (°)",
    detectorYaw: "Detector Yaw (°)",
    detectorPitch: "Detector Pitch (°)",
    frameDuration: "Frame Duration (μs)",
    timeResolution: "Time Resolution (ps)",
    tdcBitDepth: "TDC Bit Depth / Max Count",
    tdcBits: "bits",
    tdcMaxCount: "Max Count:",
    quantumEfficiency: "Quantum Efficiency",
    apertureDiameter: "Aperture Diameter (m)",
    systemEfficiency: "System Efficiency",
    filterBandwidth: "Filter Bandwidth (nm)",
    darkCountRate: "Dark Count Rate (cps)",
    calculatedValues: "Calculated Values",
    maxDistance: "Max Measurable Distance:",
    envLaser: "Environment & Laser",
    laserMode: "Laser Mode",
    laserModePulsed: "Pulsed",
    laserModeCW: "CW",
    solarIrradiance: "Solar Irradiance (W/m²/nm)",
    atmosphericAttenuation: "Atmospheric Attenuation",
    laserWavelength: "Laser Wavelength (nm)",
    laserAvgPower: "Average Laser Power (W)",
    transmitterDivergence: "Transmitter Divergence (mrad)",
    pulseWidth: "Pulse Width (ns)",
    repetitionFreq: "Repetition Frequency",
    pulseEnergy: "Single Pulse Energy:",
    distanceResolution: "Distance Resolution:",
    peakPower: "Peak Power:",
    cwMode: "Mode:",
    cwModeText: "Continuous Wave",
    simSettings: "Simulation Settings",
    nFrames: "Number of Frames",
    runtimeBudget: "Dataset Budget",
    workingSet: "Estimated Working Set",
    runtimeSafe: "Runtime load is suitable for interactive simulation.",
    runtimeCaution: "This configuration is heavy; reduce frames if the browser becomes sluggish.",
    runtimeBlocked: "This configuration is too large for safe browser-side generation.",
    recommendedFrames: "Recommended frames",
    detectorInfo: "Detector at (0, 1, 0) | Ground at Y=0",
    activeDrone: "Active Drone",
    dronePosition: "Target Position",
    laserVisual: "Laser",
    telescopeModel: "Telescope",
    controlsTitle: "Controls:",
    controlsInfo: "Drag to orbit, Scroll to zoom, Right-click to pan.",
    manualControlsInfo: "WASD translate, R/F altitude, Q/E yaw, right-drag to aim.",
    detectorView: "Detector View",
    resultsTitle: "Simulation Results",
    detectedPhotons: "Detected Photons",
    noisePhotons: "Detected Noise Photons",
    incidentPhotons: "Incident Photons (Signal)",
    peakPileup: "Peak Pile-up Factor",
    pileupHigh: "High (Saturation)",
    pileupModerate: "Moderate (Non-linear)",
    pileupLow: "Low (Linear Response)",
    photonCounting: "Photon Counting",
    groundTruth: "Ground Truth Trajectory",
    incidentPhotonsCanvas: "Incident Photons",
  },
  zh: {
    title: "SPAD 模拟器",
    languageToggle: "EN / 中文",
    runSimulation: "运行模拟",
    runBackendSimulation: "后端运行模拟",
    backendSimulating: "后端运行中...",
    backendCompute: "后端算力",
    backendJobStatus: "后端任务",
    backendUnavailable: "后端服务未连接。",
    backendMode: "后端",
    observedCounts: "观测计数",
    snrDb: "信噪比",
    deadTimeLoss: "死时间损失",
    signalPhotons: "信号光子：",
    backgroundPhotons: "场景杂散光子：",
    laserSignalRate: "激光反射计数率：",
    solarSignalRate: "太阳反射计数率：",
    saturationWarning: "探测器饱和预警",
    visibilityRatio: "可见比例：",
    payloadOmitted: "已省略大载荷：",
    sampleRate: "采样率：",
    refresh: "刷新",
    simulating: "模拟中...",
    previewTrajectory: "预览轨迹",
    downloadData: "下载数据",
    targetParams: "目标参数",
    targetType: "目标类型",
    targetTypeBall: "网球",
    targetTypeBlade: "螺旋桨叶片",
    targetTypeDrone: "无人机",
    motionType: "运动模式",
    motionTypeFixed: "固定位置",
    motionTypePath: "路径规划",
    motionTypeGravity: "重力模拟",
    motionTypeRotation: "旋转模式",
    centerX: "中心 X",
    altitudeY: "高度 Y",
    centerZ: "中心 Z",
    velX: "速度 X",
    velY: "速度 Y",
    velZ: "速度 Z",
    reflectivity: "反射率 (0-1)",
    bodyReflectivity: "机身反射率 (0-1)",
    propReflectivity: "桨叶反射率 (0-1)",
    restitution: "恢复系数 (弹性)",
    dynamicModulation: "动态目标调制",
    bladeLength: "叶片尺寸/长度 (m)",
    rotationRadius: "旋转半径 (m)",
    rotationSpeed: "转速 (RPM)",
    rotationSpeedSegment: "转速",
    bladePitch: "叶片俯仰角 (°)",
    dronePitch: "无人机俯仰角 (°)",
    droneScale: "无人机缩放比例",
    dronePreset: "无人机预设",
    droneMass: "质量：",
    droneMaxSpeed: "最大速度：",
    droneSize: "尺寸：",
    droneRotor: "悬停转速：",
    manualFlight: "键鼠手飞",
    manualSpeed: "手飞速度",
    capturePose: "设当前位置为起飞点",
    startFlightRecording: "开始录制",
    stopFlightRecording: "停止录制",
    clearFlightRecording: "清除录制",
    recordedFlight: "已录制轨迹",
    recordedDuration: "录制时长",
    samples: "样本",
    manualFlightState: "飞控状态",
    pathPlanning: "路径规划",
    pathPlanningDesc: "为目标的飞行路径定义一系列航点。可以为每个路段设置速度。",
    waypoint: "航点",
    speed: "速度",
    duration: "用时",
    addWaypoint: "添加航点",
    remove: "移除",
    rotationSpeedPlanning: "转速规划",
    rotationSpeedPlanningDesc: "定义时间点以创建可变转速曲线。RPM将在点之间进行线性插值。",
    time: "时间",
    rpm: "转速",
    addRotationKeyframe: "添加时间点",
    propeller1: "桨叶1",
    propeller2: "桨叶2",
    propeller3: "桨叶3",
    propeller4: "桨叶4",
    customBlade: "自定义螺旋桨形状",
    customBladeDesc: "上传一张图片作为目标。将从图像的暗部区域提取形状。尺寸由“叶片尺寸”控制。",
    customBladeRealismDesc: "图像中的灰度值现在会调节反射率。纯黑色为全反射率，而深灰色区域在模拟中会显得更暗。",
    originalImage: "原始图像",
    clickToUpload: "点击上传",
    extractedShape: "提取的形状",
    shapeWillAppear: "形状将在此处显示。",
    detectorParams: "探测器参数",
    detectorPreset: "探测器预设",
    detectorPresetCustom: "自定义探测器",
    pixelPitch: "像元间距：",
    pdpAtWavelength: "当前波长 PDP：",
    deadTime: "死时间：",
    irfFwhm: "IRF 半高宽：",
    resWidth: "分辨率 宽",
    resHeight: "分辨率 高",
    fov: "视场角 (°)",
    detectorYaw: "探测器偏航角 (°)",
    detectorPitch: "探测器俯仰角 (°)",
    frameDuration: "帧持续时间 (μs)",
    timeResolution: "时间分辨率 (ps)",
    tdcBitDepth: "TDC 位深 / 最大计数",
    tdcBits: "位",
    tdcMaxCount: "最大计数值:",
    quantumEfficiency: "量子效率",
    apertureDiameter: "孔径直径 (m)",
    systemEfficiency: "系统效率",
    filterBandwidth: "滤光片带宽 (nm)",
    darkCountRate: "暗计数率 (cps)",
    calculatedValues: "计算值",
    maxDistance: "最大可测距离:",
    envLaser: "环境与激光",
    laserMode: "激光模式",
    laserModePulsed: "脉冲",
    laserModeCW: "连续波",
    solarIrradiance: "太阳辐照度 (W/m²/nm)",
    atmosphericAttenuation: "大气衰减",
    laserWavelength: "激光波长 (nm)",
    laserAvgPower: "平均激光功率 (W)",
    transmitterDivergence: "发射光束发散角 (mrad)",
    pulseWidth: "脉冲宽度 (ns)",
    repetitionFreq: "重复频率",
    pulseEnergy: "单脉冲能量:",
    distanceResolution: "距离分辨率:",
    peakPower: "峰值功率:",
    cwMode: "模式:",
    cwModeText: "连续波",
    simSettings: "模拟设置",
    nFrames: "帧数",
    runtimeBudget: "数据预算",
    workingSet: "估计工作集",
    runtimeSafe: "当前负载适合前端交互式仿真。",
    runtimeCaution: "该配置较重；若浏览器卡顿，请降低帧数。",
    runtimeBlocked: "该配置过大，不适合在浏览器端安全生成。",
    recommendedFrames: "建议帧数",
    detectorInfo: "探测器在 (0, 1, 0) | 地面为 Y=0",
    activeDrone: "当前无人机",
    dronePosition: "目标位置",
    laserVisual: "激光",
    telescopeModel: "望远镜",
    controlsTitle: "控制:",
    controlsInfo: "拖动旋转, 滚轮缩放, 右键平移。",
    manualControlsInfo: "WASD 平移，R/F 升降，Q/E 偏航，右键拖动调整朝向。",
    detectorView: "探测器视角",
    resultsTitle: "模拟结果",
    detectedPhotons: "探测到的光子",
    noisePhotons: "探测到的噪声光子",
    incidentPhotons: "入射光子 (信号)",
    peakPileup: "峰值堆积因子",
    pileupHigh: "高 (饱和)",
    pileupModerate: "中 (非线性)",
    pileupLow: "低 (线性响应)",
    photonCounting: "光子计数",
    groundTruth: "真实轨迹",
    incidentPhotonsCanvas: "入射光子",
  },
};

@Injectable({
  providedIn: 'root',
})
export class LocalizationService {
  private language = signal<'en' | 'zh'>('zh');

  public toggleLanguage(): void {
    this.language.update(lang => (lang === 'en' ? 'zh' : 'en'));
  }

  public t(key: TranslationKey) {
    return computed(() => dictionary[this.language()][key] || key);
  }
}
